
package br.com.gestao.view.service.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileTransferer", targetNamespace = "http://webservice.service.view.gestao.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileTransferer {


    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "licenca", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.Licenca")
    @ResponseWrapper(localName = "licencaResponse", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.LicencaResponse")
    public byte[] licenca(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.DownloadResponse")
    public byte[] download(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "licencaNumeroContrato", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.LicencaNumeroContrato")
    @ResponseWrapper(localName = "licencaNumeroContratoResponse", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.LicencaNumeroContratoResponse")
    public String licencaNumeroContrato(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "uploadArquivoClinicaPDF", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.UploadArquivoClinicaPDF")
    @ResponseWrapper(localName = "uploadArquivoClinicaPDFResponse", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.UploadArquivoClinicaPDFResponse")
    public void uploadArquivoClinicaPDF(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        byte[] arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "uploadArquivoClinicaIMAGE", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.UploadArquivoClinicaIMAGE")
    @ResponseWrapper(localName = "uploadArquivoClinicaIMAGEResponse", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.UploadArquivoClinicaIMAGEResponse")
    public void uploadArquivoClinicaIMAGE(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        byte[] arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "uploadArquivoClinicaOFFICE", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.UploadArquivoClinicaOFFICE")
    @ResponseWrapper(localName = "uploadArquivoClinicaOFFICEResponse", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.UploadArquivoClinicaOFFICEResponse")
    public void uploadArquivoClinicaOFFICE(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        byte[] arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "informarDadosCliente", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.InformarDadosCliente")
    @ResponseWrapper(localName = "informarDadosClienteResponse", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.InformarDadosClienteResponse")
    public void informarDadosCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "upload", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://webservice.service.view.gestao.com.br/", className = "br.com.gestao.view.service.webservice.UploadResponse")
    public void upload(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1);

}
